// Реальні GPS координати міст по регіонам (lat/lng)
export const citiesData = {
  Kyiv: {
    bounds: [
      [49.9, 29.5],
      [51.5, 32.0],
    ],
    center: [50.45, 30.52],
    zoom: 9,
    cities: [
      {
        id: "kyiv-01",
        name: "Київ",
        lat: 50.4501,
        lng: 30.5234,
        description: "Столиця України",
        population: "2.9 млн",
        founded: "482 р.",
        info: "Одна з найстаріших і найбільших міст Європи. Розташована на річці Дніпро.",
        attractions: [
          "Майдан Незалежності",
          "Софійський собор",
          "Золоті ворота",
        ],
      },
      {
        id: "kyiv-02",
        name: "Ірпінь",
        lat: 50.5213,
        lng: 30.2495,
        description: "Місто-супутник Києва",
        population: "0.27 млн",
        founded: "1898 р.",
        info: "Сучасне місто з розвиненою IT-індустрією та зеленими кварталами.",
        attractions: ["Парк Ірпіня", "Ірпінський водоспад"],
      },
      {
        id: "kyiv-03",
        name: "Бровари",
        lat: 50.5108,
        lng: 30.7897,
        description: "Промислове місто",
        population: "0.1 млн",
        founded: "1628 р.",
        info: "Одне з найбільших промислових міст Київщини.",
        attractions: ["Квартал культури"],
      },
      {
        id: "kyiv-04",
        name: "Біла Церква",
        lat: 49.811,
        lng: 30.1106,
        description: "Давнє місто",
        population: "0.21 млн",
        founded: "1032 р.",
        info: "Стародавнє місто, засноване Ярославом Мудрим.",
        attractions: ["Парк Олександрія"],
      },
    ],
  },
  Lviv: {
    bounds: [
      [48.9, 22.5],
      [51.0, 25.5],
    ],
    center: [49.84, 24.03],
    zoom: 9,
    cities: [
      {
        id: "lviv-01",
        name: "Львів",
        lat: 49.8397,
        lng: 24.0297,
        description: "Культурна столиця",
        population: "0.75 млн",
        founded: "1256 р.",
        info: "Місто з багатою архітектурою та культурою. Серце Галичини.",
        attractions: ["Площа Ринок", "Оперний театр", "Личаківський некрополь"],
      },
      {
        id: "lviv-02",
        name: "Дрогобич",
        lat: 49.349,
        lng: 23.5055,
        description: "Місто нафти і солі",
        population: "0.074 млн",
        founded: "1392 р.",
        info: "Давнє місто з унікальними сіллю і нафтою.",
        attractions: ["Церква Св. Трійці"],
      },
      {
        id: "lviv-03",
        name: "Трускавець",
        lat: 49.283,
        lng: 23.5133,
        description: "Курорт",
        population: "0.03 млн",
        founded: "1461 р.",
        info: "Відомий бальнеологічний курорт.",
        attractions: ["Джерело Нафтуся"],
      },
      {
        id: "lviv-04",
        name: "Стрий",
        lat: 49.2589,
        lng: 23.8538,
        description: "Місто на Стрию",
        population: "0.057 млн",
        founded: "1431 р.",
        info: "Одне з найбільших міст Львівщини.",
        attractions: ["Стрийський замок"],
      },
    ],
  },
  Odessa: {
    bounds: [
      [45.5, 28.5],
      [47.8, 32.0],
    ],
    center: [46.48, 30.73],
    zoom: 9,
    cities: [
      {
        id: "odessa-01",
        name: "Одеса",
        lat: 46.4825,
        lng: 30.7233,
        description: "Перлина Чорного моря",
        population: "1.01 млн",
        founded: "1794 р.",
        info: "Великий портовий город з унікальною культурою.",
        attractions: ["Оперний театр", "Потьомкінські сходи", "Дерибасівська"],
      },
      {
        id: "odessa-02",
        name: "Ізмаїл",
        lat: 45.3533,
        lng: 28.8452,
        description: "Місто на Дунаї",
        population: "0.07 млн",
        founded: "1580 р.",
        info: "Стратегічне місто на Дунаї.",
        attractions: ["Фортеця Ізмаїл"],
      },
      {
        id: "odessa-03",
        name: "Білгород-Дністровський",
        lat: 46.1876,
        lng: 30.3467,
        description: "Давньоруське місто",
        population: "0.049 млн",
        founded: "6 ст.",
        info: "Одне з найдавніших міст України.",
        attractions: ["Акерманська фортеця"],
      },
    ],
  },
  Kharkiv: {
    bounds: [
      [49.0, 35.0],
      [51.5, 38.0],
    ],
    center: [49.99, 36.23],
    zoom: 9,
    cities: [
      {
        id: "kharkiv-01",
        name: "Харків",
        lat: 49.9935,
        lng: 36.2304,
        description: "Місто науки і техніки",
        population: "1.43 млн",
        founded: "1654 р.",
        info: "Другий за розміром мегаполіс України.",
        attractions: ["Площа Свободи", "Госпром"],
      },
      {
        id: "kharkiv-02",
        name: "Чугуїв",
        lat: 49.8385,
        lng: 36.6932,
        description: "Козацьке місто",
        population: "0.032 млн",
        founded: "1638 р.",
        info: "Батьківщина художника Іллі Рєпіна.",
        attractions: ["Музей Рєпіна"],
      },
      {
        id: "kharkiv-03",
        name: "Лозова",
        lat: 48.8866,
        lng: 36.3175,
        description: "Залізничний вузол",
        population: "0.055 млн",
        founded: "1869 р.",
        info: "Важливий залізничний вузол.",
        attractions: ["Успенський собор"],
      },
    ],
  },
  Dnipropetrovsk: {
    bounds: [
      [47.5, 33.0],
      [49.5, 36.5],
    ],
    center: [48.46, 35.04],
    zoom: 9,
    cities: [
      {
        id: "dnipro-01",
        name: "Дніпро",
        lat: 48.4647,
        lng: 35.0462,
        description: "Індустріальне серце",
        population: "0.98 млн",
        founded: "1776 р.",
        info: "Один з головних промислових центрів України.",
        attractions: ["Монастирський острів", "Набережна"],
      },
      {
        id: "dnipro-02",
        name: "Кривий Ріг",
        lat: 47.9135,
        lng: 33.3539,
        description: "Місто заліза",
        population: "0.62 млн",
        founded: "1775 р.",
        info: "Одне з найдовших міст світу — 126 км.",
        attractions: ["Місто криворізьке"],
      },
      {
        id: "dnipro-03",
        name: "Кам'янське",
        lat: 48.5087,
        lng: 34.6176,
        description: "Металургійне місто",
        population: "0.25 млн",
        founded: "1750 р.",
        info: "Металургійний центр на берегах Дніпра.",
        attractions: ["Набережна"],
      },
    ],
  },
  Cherkasy: {
    bounds: [
      [48.8, 29.5],
      [50.0, 32.5],
    ],
    center: [49.44, 32.06],
    zoom: 9,
    cities: [
      {
        id: "cherkasy-01",
        name: "Черкаси",
        lat: 49.4309,
        lng: 32.0599,
        description: "Козацька столиця",
        population: "0.28 млн",
        founded: "1286 р.",
        info: "Місто на березі Дніпра, центр козацького краю.",
        attractions: ["Набережна", "Парк Берег"],
      },
      {
        id: "cherkasy-02",
        name: "Умань",
        lat: 48.7469,
        lng: 30.2188,
        description: "Сад і паломники",
        population: "0.085 млн",
        founded: "1616 р.",
        info: "Відоме дендропарком Софіївка.",
        attractions: ["Дендропарк Софіївка"],
      },
      {
        id: "cherkasy-03",
        name: "Канів",
        lat: 49.7497,
        lng: 31.4679,
        description: "Місто Шевченка",
        population: "0.025 млн",
        founded: "1144 р.",
        info: "Місто, де похований Тарас Шевченко.",
        attractions: ["Могила Тараса Шевченка", "Тарасова Гора"],
      },
    ],
  },
  Rivne: {
    bounds: [
      [50.0, 24.5],
      [51.5, 27.5],
    ],
    center: [50.62, 26.25],
    zoom: 9,
    cities: [
      {
        id: "rivne-01",
        name: "Рівне",
        lat: 50.6199,
        lng: 26.2516,
        description: "Бурштинова столиця",
        population: "0.26 млн",
        founded: "1283 р.",
        info: "Адміністративний центр Рівненщини.",
        attractions: ["Костел Св. Антонія", "Палац Любомирських"],
      },
      {
        id: "rivne-02",
        name: "Острог",
        lat: 50.3274,
        lng: 26.5192,
        description: "Перший університет",
        population: "0.015 млн",
        founded: "1100 р.",
        info: "Острозька Академія — перший університет України.",
        attractions: ["Острозька академія", "Замок Острозьких"],
      },
      {
        id: "rivne-03",
        name: "Дубно",
        lat: 50.4116,
        lng: 25.737,
        description: "Замкове місто",
        population: "0.037 млн",
        founded: "1100 р.",
        info: "Давнє місто-фортеця.",
        attractions: ["Дубнівський замок"],
      },
    ],
  },
  Zakarpattia: {
    bounds: [
      [47.9, 22.0],
      [49.0, 24.5],
    ],
    center: [48.62, 22.3],
    zoom: 9,
    cities: [
      {
        id: "zakarpattia-01",
        name: "Ужгород",
        lat: 48.6208,
        lng: 22.298,
        description: "Карпатська столиця",
        population: "0.116 млн",
        founded: "895 р.",
        info: "Красиве місто в передгір'ях Карпат.",
        attractions: ["Ужгородський замок", "Набережна Ужа"],
      },
      {
        id: "zakarpattia-02",
        name: "Мукачево",
        lat: 48.4438,
        lng: 22.7106,
        description: "Замкове місто",
        population: "0.084 млн",
        founded: "895 р.",
        info: "Місто відоме замком Паланок.",
        attractions: ["Замок Паланок"],
      },
      {
        id: "zakarpattia-03",
        name: "Хуст",
        lat: 48.1692,
        lng: 23.2971,
        description: "Замкове місто Тиси",
        population: "0.028 млн",
        founded: "1090 р.",
        info: "Давнє місто з руїнами замку.",
        attractions: ["Хустський замок"],
      },
    ],
  },
  Chernihiv: {
    bounds: [
      [50.5, 30.5],
      [52.5, 34.5],
    ],
    center: [51.49, 31.29],
    zoom: 9,
    cities: [
      {
        id: "chernihiv-01",
        name: "Чернігів",
        lat: 51.494,
        lng: 31.2958,
        description: "Місто монастирів",
        population: "0.29 млн",
        founded: "907 р.",
        info: "Одне з найстаріших міст Русі.",
        attractions: ["Спасо-Преображенський собор", "Дитинець"],
      },
      {
        id: "chernihiv-02",
        name: "Ніжин",
        lat: 51.0484,
        lng: 31.8799,
        description: "Університетське місто",
        population: "0.072 млн",
        founded: "1147 р.",
        info: "Батьківщина Гоголя, місто з університетом.",
        attractions: ["Університет ім. Гоголя"],
      },
    ],
  },
  Chernivtsi: {
    bounds: [
      [47.8, 25.0],
      [48.6, 26.5],
    ],
    center: [48.29, 25.93],
    zoom: 10,
    cities: [
      {
        id: "chernivtsi-01",
        name: "Чернівці",
        lat: 48.2921,
        lng: 25.9354,
        description: "Маленький Відень",
        population: "0.26 млн",
        founded: "1408 р.",
        info: "Місто з унікальною австро-угорською архітектурою.",
        attractions: [
          "Університет (Резиденція митрополитів)",
          "Театральна площа",
        ],
      },
    ],
  },
  Donetsk: {
    bounds: [
      [47.0, 36.5],
      [49.0, 39.0],
    ],
    center: [47.98, 37.8],
    zoom: 9,
    cities: [
      {
        id: "donetsk-01",
        name: "Маріуполь",
        lat: 47.0948,
        lng: 37.5421,
        description: "Місто сталі і моря",
        population: "0.43 млн",
        founded: "1778 р.",
        info: "Великий портовий і металургійний город на Азовському морі.",
        attractions: ["Морський порт", "Грецькі квартали"],
      },
      {
        id: "donetsk-02",
        name: "Краматорськ",
        lat: 48.7303,
        lng: 37.5558,
        description: "Машинобудівний центр",
        population: "0.15 млн",
        founded: "1868 р.",
        info: "Адміністративна столиця підконтрольної Донеччини.",
        attractions: ["Парк культури"],
      },
      {
        id: "donetsk-03",
        name: "Слов'янськ",
        lat: 48.8576,
        lng: 37.6094,
        description: "Соляне місто",
        population: "0.1 млн",
        founded: "1645 р.",
        info: "Відоме солоними озерами та санаторіями.",
        attractions: ["Святі гори", "Ропне озеро"],
      },
    ],
  },
  Zaporizhia: {
    bounds: [
      [46.8, 33.5],
      [48.5, 36.5],
    ],
    center: [47.85, 35.09],
    zoom: 9,
    cities: [
      {
        id: "zaporizhia-01",
        name: "Запоріжжя",
        lat: 47.8388,
        lng: 35.1396,
        description: "Козацька фортеця",
        population: "0.73 млн",
        founded: "1770 р.",
        info: "Промислове місто козаків на острові Хортиця.",
        attractions: ["Острів Хортиця", "Дніпрогес"],
      },
      {
        id: "zaporizhia-02",
        name: "Бердянськ",
        lat: 46.7645,
        lng: 36.8215,
        description: "Азовський курорт",
        population: "0.12 млн",
        founded: "1827 р.",
        info: "Курортне місто на Азовському морі.",
        attractions: ["Приморський парк", "Пляжі Бердянська"],
      },
    ],
  },
  Ivano_Frankivsk: {
    bounds: [
      [47.8, 23.7],
      [49.1, 25.3],
    ],
    center: [48.92, 24.71],
    zoom: 9,
    cities: [
      {
        id: "ivano-01",
        name: "Івано-Франківськ",
        lat: 48.9226,
        lng: 24.7111,
        description: "Ворота в Карпати",
        population: "0.24 млн",
        founded: "1662 р.",
        info: "Жваве галицьке місто, ворота до Карпат.",
        attractions: ["Ратуша", "Вірменський костел"],
      },
      {
        id: "ivano-02",
        name: "Коломия",
        lat: 48.5273,
        lng: 25.0402,
        description: "Гуцульська столиця",
        population: "0.065 млн",
        founded: "1240 р.",
        info: "Місто гуцульської культури.",
        attractions: ["Музей Писанки"],
      },
      {
        id: "ivano-03",
        name: "Яремче",
        lat: 48.4584,
        lng: 24.5573,
        description: "Карпатський курорт",
        population: "0.011 млн",
        founded: "1413 р.",
        info: "Відомий карпатський курорт.",
        attractions: ["Яремчанський водоспад"],
      },
    ],
  },
  Khmelnytskyi: {
    bounds: [
      [48.6, 25.7],
      [50.3, 28.0],
    ],
    center: [49.42, 26.99],
    zoom: 9,
    cities: [
      {
        id: "khmelnytskyi-01",
        name: "Хмельницький",
        lat: 49.4225,
        lng: 26.9872,
        description: "Промислове місто",
        population: "0.27 млн",
        founded: "1434 р.",
        info: "Сучасне місто Поділля.",
        attractions: ["Подільський краєзнавчий музей"],
      },
      {
        id: "khmelnytskyi-02",
        name: "Кам'янець-Подільський",
        lat: 48.6779,
        lng: 26.5736,
        description: "Місто-фортеця",
        population: "0.096 млн",
        founded: "12 ст.",
        info: "Місто з середньовічною фортецею і каньйоном.",
        attractions: ["Кам'янець-Подільська фортеця", "Смотрицький каньйон"],
      },
    ],
  },
  Kirovohrad: {
    bounds: [
      [47.6, 30.5],
      [49.0, 33.5],
    ],
    center: [48.51, 32.26],
    zoom: 9,
    cities: [
      {
        id: "kirovohrad-01",
        name: "Кропивницький",
        lat: 48.5079,
        lng: 32.2623,
        description: "Центр степу",
        population: "0.22 млн",
        founded: "1754 р.",
        info: "Місто в центрі України.",
        attractions: ["Театральне коло"],
      },
    ],
  },
  Luhansk: {
    bounds: [
      [47.9, 37.5],
      [49.5, 40.2],
    ],
    center: [48.57, 39.33],
    zoom: 9,
    cities: [
      {
        id: "luhansk-01",
        name: "Сєвєродонецьк",
        lat: 48.9475,
        lng: 38.4884,
        description: "Хімічне місто",
        population: "0.1 млн",
        founded: "1934 р.",
        info: "Тимчасова столиця Луганщини.",
        attractions: ["Парк культури"],
      },
    ],
  },
  Mykolaiv: {
    bounds: [
      [46.5, 30.5],
      [47.7, 34.0],
    ],
    center: [47.0, 32.0],
    zoom: 9,
    cities: [
      {
        id: "mykolaiv-01",
        name: "Миколаїв",
        lat: 46.9739,
        lng: 31.9929,
        description: "Суднобудівне місто",
        population: "0.48 млн",
        founded: "1789 р.",
        info: "Велике суднобудівне місто.",
        attractions: ["Набережна", "Зоопарк"],
      },
    ],
  },
  Poltava: {
    bounds: [
      [48.5, 32.5],
      [50.5, 35.5],
    ],
    center: [49.59, 34.54],
    zoom: 9,
    cities: [
      {
        id: "poltava-01",
        name: "Полтава",
        lat: 49.5883,
        lng: 34.5514,
        description: "Місто слави",
        population: "0.28 млн",
        founded: "1174 р.",
        info: "Місто Полтавської битви та козацької слави.",
        attractions: [
          "Монумент Полтавської битви",
          "Хрестовоздвиженський монастир",
        ],
      },
      {
        id: "poltava-02",
        name: "Кременчук",
        lat: 49.0726,
        lng: 33.4152,
        description: "Автомобільне місто",
        population: "0.22 млн",
        founded: "1571 р.",
        info: "Місто заводу КрАЗ.",
        attractions: ["Кременчуцьке водосховище"],
      },
    ],
  },
  Sumu: {
    bounds: [
      [50.0, 32.5],
      [52.5, 35.5],
    ],
    center: [50.91, 34.8],
    zoom: 9,
    cities: [
      {
        id: "sumu-01",
        name: "Суми",
        lat: 50.9077,
        lng: 34.7981,
        description: "Університетське місто",
        population: "0.25 млн",
        founded: "1655 р.",
        info: "Зелене місто з розвиненою освітою.",
        attractions: ["Спасо-Преображенський собор"],
      },
    ],
  },
  Ternopil: {
    bounds: [
      [48.6, 24.7],
      [50.0, 26.4],
    ],
    center: [49.55, 25.59],
    zoom: 9,
    cities: [
      {
        id: "ternopil-01",
        name: "Тернопіль",
        lat: 49.5535,
        lng: 25.5948,
        description: "Озерне місто",
        population: "0.22 млн",
        founded: "1540 р.",
        info: "Красиве місто на березі ставу.",
        attractions: ["Тернопільський ставок", "Домініканський монастир"],
      },
      {
        id: "ternopil-02",
        name: "Чортків",
        lat: 49.0094,
        lng: 25.7975,
        description: "Замкове місто",
        population: "0.03 млн",
        founded: "1453 р.",
        info: "Місто з відомим замком.",
        attractions: ["Чортківський замок"],
      },
    ],
  },
  Vinnytsia: {
    bounds: [
      [48.2, 27.0],
      [49.8, 30.3],
    ],
    center: [49.23, 28.47],
    zoom: 9,
    cities: [
      {
        id: "vinnytsia-01",
        name: "Вінниця",
        lat: 49.2331,
        lng: 28.4682,
        description: "Місто Пирогова",
        population: "0.37 млн",
        founded: "1363 р.",
        info: "Місто з фонтаном Рошен.",
        attractions: ["Фонтан Рошен", "Музей Пирогова"],
      },
    ],
  },
  Volyn: {
    bounds: [
      [50.3, 23.5],
      [52.0, 26.0],
    ],
    center: [51.24, 25.32],
    zoom: 9,
    cities: [
      {
        id: "volyn-01",
        name: "Луцьк",
        lat: 50.7472,
        lng: 25.3254,
        description: "Замкове місто",
        population: "0.22 млн",
        founded: "1085 р.",
        info: "Столиця Волині зі знаменитим Луцьким замком.",
        attractions: ["Луцький замок", "Кафедральний собор"],
      },
    ],
  },
  Zhytomyr: {
    bounds: [
      [49.9, 27.2],
      [51.2, 30.0],
    ],
    center: [50.25, 28.66],
    zoom: 9,
    cities: [
      {
        id: "zhytomyr-01",
        name: "Житомир",
        lat: 50.2547,
        lng: 28.6587,
        description: "Стародавнє місто",
        population: "0.26 млн",
        founded: "884 р.",
        info: "Одне з найстаріших міст України.",
        attractions: ["Собор Св. Михайла", "Парк культури"],
      },
    ],
  },
  KyivCity: {
    bounds: [
      [50.3, 30.3],
      [50.6, 30.8],
    ],
    center: [50.4501, 30.5234],
    zoom: 12,
    cities: [
      {
        id: "kyivcity-01",
        name: "Київ (місто)",
        lat: 50.4501,
        lng: 30.5234,
        description: "Столиця України",
        population: "2.9 млн",
        founded: "482 р.",
        info: "Столиця та найбільше місто України.",
        attractions: ["Майдан", "Хрещатик", "Лавра"],
      },
    ],
  },
  Crimea: {
    bounds: [
      [44.4, 32.5],
      [46.2, 36.7],
    ],
    center: [45.35, 34.1],
    zoom: 9,
    cities: [
      {
        id: "crimea-01",
        name: "Сімферополь",
        lat: 44.9521,
        lng: 34.1024,
        description: "Столиця Криму",
        population: "0.34 млн",
        founded: "1784 р.",
        info: "Адміністративний центр тимчасово окупованого Кримського півострова.",
        attractions: ["Бахчисарайський ханський палац"],
      },
      {
        id: "crimea-02",
        name: "Ялта",
        lat: 44.4951,
        lng: 34.1665,
        description: "Курортна перлина",
        population: "0.079 млн",
        founded: "1145 р.",
        info: "Знаменитий кримський курорт.",
        attractions: ["Лівадійський палац", "Набережна Ялти"],
      },
    ],
  },
  Kherson: {
    bounds: [
      [45.2, 31.8],
      [47.0, 35.1],
    ],
    center: [46.64, 32.62],
    zoom: 9,
    cities: [
      {
        id: "kherson-01",
        name: "Херсон",
        lat: 46.6354,
        lng: 32.6169,
        description: "Місто арбузів",
        population: "0.28 млн",
        founded: "1778 р.",
        info: "Місто в дельті Дніпра, відоме арбузами.",
        attractions: ["Херсонська фортеця", "Гідропарк"],
      },
    ],
  },
};

export const getCitiesByRegion = (region) => {
  const data = citiesData[region];
  if (!data) return { cities: [], bounds: null, center: [49.0, 32.0], zoom: 7 };
  return data;
};

export const getCityById = (id) => {
  for (const region in citiesData) {
    const city = citiesData[region].cities.find((c) => c.id === id);
    if (city) {
      return { ...city, region };
    }
  }
  return null;
};
